Refactored iniparse, load_list, and ui commands.
The iniparse command is now working properly. Instead of trying to map
keys to environment variables, it now produces a directory hierarchy
using sections as directory names. Keys are created as files containing
their values. This approach is much cleaner than trying to eval the
results with the previous attempt at mapping.

Reworked load_list to do away with the unnecessary environment variable
creation silliness and just print the filtered list. Also did away with
the environment variable creation attempts in style, and greatly
simplified the interfaces of cprintf and topline. Now, style would only
be called once to resolve the styles into style name to color code and
tput argument maps. Both cprintf and topline are capable of reading the
style map from the STYLES environment variable and setting colors and
fonts accordingly. Hopefully, this approach will prove more reliable
than the previous attempt.

diff --git a/src/config/iniparse b/src/config/iniparse
--- a/src/config/iniparse
+++ b/src/config/iniparse
@@ -25,63 +25,47 @@
 
 usage() {
     cat << EOF
-$0 [options] [-c <file>] [-m var=key] [-p key=value]
+$0 [options] [-c <file>] [-m var=key] [-p key=value] [-o <directory>]
 
 Options:
     -c <file> | --config <file>
         Read from the specified <file> instead of standard input.
     -h | --help
         Show this help message and exit.
-    -m var=section.key | --map var=section.key
-        Map the environment variable "var" to configuration file friendly
-        name "key" in section "section".
-    -n | --no-export
-        Do not produce export statements for variables.
-    -p section.key=value | --preload section.key=value
+    -o <directory> | --output <directory>
+        Use <directory> for output instead of creating one with mktemp(1).
+    -p section/key=value | --preload section/key=value
         Preload a value for a friendly name "key" in section "section" of the
-        configuration file.
-    -u | --error-unmapped
-        Produce an error if the configuration file contains a key (friendly
-        name) that is not mapped to an environment variable.
+        configuration file. If the section and slash are omitted, the variable
+        will be an unsectioned global variable visible in all sections.
+    -u | --no-underscores
+        Do not convert spaces to underscores in section and key names when
+        producing the output files and directories.
 
-An example of the intended usage of iniparse is:
-
-eval \$(iniparse -c /path/to/config.ini \\
-    -m FOO="main.key 1" \\
-    -m BAR="main.key 2")
-
-In the above example, the value of the configuration key "key 1" in section
-[main] of the configuration file will be mapped to environment variable FOO.
-The value of the configuration key "key 2", also in section [main], will be
-mapped to environment variable BAR.
-
-The corresponding configuration file might look like this:
----
-[main]
-friendly = Hello
-friendly 2 = World
----
+This program parses an INI file and produces a hierarchical output directory
+containing the information from the file. Each section in the INI file
+creates a directory in the output path, with the values from the INI file
+exported to plain text files named according to the keys in each section. By
+default, a new temporary directory is created, the path of which is output
+after processing is finished. However, an existing directory may be specified
+instead by using the -o option. Note that the directory specified with -o
+must already exist and will not be created.
 
 The supported dialect of INI supports full-line comments but not inline ones.
 Line comments start with either # or ;. Values must NOT be quoted but may
 contain spaces. Multi-line values are supported if subsequent lines are
 indented at least to the level of the start of the value in the first line
-(or one position after the = if the first line is blank).
+(or one position after the = if the first line is blank). Section names
+containing slashes will produce a hierarchy of subdirectories.
 
 Basic variable substitution within the configuration system is supported
 using the syntax \${key}, where key is another key in the configuration to
 be replaced by a value wherever \${key} is used in a value. Preloaded values
-for keys are supported by giving the -p option before each section.key=value
-mapping. Any preloaded values set for keys that are mapped to environment
-variables become the default values for those environment variables if the
-key is missing from the configuration file. Thus, -p and -m can be used
-together to permit a configuration file to supply optional overrides for an
-existing value.
-
-By default, all environment variable expressions generated by loadconfig are
-followed by export statements. This behavior can be disabled with the -n
-option. In addition, unmapped keys in the configuration file are typically
-ignored. The -u option will cause any unmapped keys to produce an error.
+for keys are supported by giving the -p option before each section/key=value
+mapping. Any preloaded values set for keys that do not appear in the INI
+file are written to the output directory as-is, while preloaded values for
+keys that are present in the INI file will be overridden by the values
+from the INI file.
 
 Finally, it is worth noting the advantages over using an INI configuration
 file as opposed to sourcing a configuration file made of shell code. First, a
@@ -90,7 +74,9 @@ becomes a potentially executable configuration, which does not enforce a
 separation of mechanism and policy. Second, the INI format is a little
 easier for most humans and read and write. This benefit is enhanced on Linux
 systems, since many editors ship with syntax highlighting support for the INI
-format already.
+format already. With this script, one can produce a friendly user-facing INI
+file, then process it into a directory hierarchy that is simple to use with
+shell scripts.
 EOF
 }
 
@@ -112,10 +98,10 @@ self=$(readlink -e "$0")
 whereami=$(dirname "${self}")
 
 
-config=
-map=
-opts=
 preload=
+config=
+output=
+underscores=1
 
 while [ $# -ne 0 ]; do
     case "$1" in
@@ -127,31 +113,26 @@ while [ $# -ne 0 ]; do
             usage
             exit 0
         ;;
-        -m|--map)
-            if echo "$2" | grep -q '='; then
-                map=$(concat_line "${map}" "$2")
-                shift 2
-            else
-                echo "Not a section.name=value pair: $2" >&2
-                exit 2
-            fi
-        ;;
-        -n|--no-export)
-            opts="${opts} noexport"
-            shift
+        -o|--output)
+            output="$2"
+            shift 2
         ;;
         -p|--preload)
             if echo "$2" | grep -q "="; then
                 preload=$(concat_line "${preload}" "$2")
                 shift 2
             else
-                echo "Not a section.name=value pair: <$2>" >&2
+                echo "Preload: not a section/name=value pair: <$2>" >&2
                 exit 2
             fi
         ;;
-        -u|--error-unmapped)
-            opts="${opts} errunmapped"
+        -u|--no-underscores)
+            underscores=0
             shift
+        ;;
+        *)
+            echo "Invalid option. Try -h or --help for help." >&2
+            exit 2
         ;;
     esac
 done
@@ -159,13 +140,28 @@ done
 
 # When no config file is specified, read from standard input
 if [ -z "${config}" ]; then
-    cfgdata=$(cat)
+    cfgdata=$(cat) || exit 1
 else
-    cfgdata=$(cat "${config}")
+    cfgdata=$(cat "${config}") || exit
 fi
 
-data=$(printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n' \
-    "${opts}" "${config}" "${preload}" "---" "${map}" "---" "${cfgdata}")
-#
+data=$(printf '%s\n%s\n%s\n%s\n' "${config}" "${preload}" "---" "${cfgdata}")
 
-echo "${data}" | awk -f "${whereami}/iniparse.awk"
+
+# Resolve the output location
+if [ -n "${output}" ]; then
+    if [ ! -d "${output}" ]; then
+        echo "Output directory does not exist: ${output}" >&2
+        exit 1
+    fi
+else
+    output=$(mktemp -d)
+fi
+
+
+# Awk does the heavy lifting here
+(cd "${output}" && echo "${data}" | awk -v underscores=${underscores} -f "${whereami}/iniparse.awk")
+status=$?
+
+echo "${output}"
+exit ${status}
